-- Start of using UsCoinDB
USE UsCoinDB;

INSERT INTO CoinValue VALUES(1, "British New World Issues", 0, "");

INSERT INTO CoinValue VALUES(2, "Classic Commemoratives", 0, "Collecting United States commemorative coins is like gathering snapshots of an album of important events, places, and people in the nation's history. Because they represent so many different aspects of America -- from wars and Olympic games to presidents, state parks, and historical landmarks, every collector can assemble a set with its own special significance.

All U!!S!! comermorative coins are issued as legal tender, though in most cases the precious metal of the coins surpasses their face values. The weight and fineness for commemoratives follow those of standard-issue gold, silver, and clad coins.");

INSERT INTO CoinValue VALUES(3, "Modern Commemoratives", 0, "Collecting United States commemorative coins is like gathering snapshots of an album of important events, places, and people in the nation's history. Because they represent so many different aspects of America -- from wars and Olympic games to presidents, state parks, and historical landmarks, every collector can assemble a set with its own special significance.

All U!!S!! comermorative coins are issued as legal tender, though in most cases the precious metal of the coins surpasses their face values. The weight and fineness for commemoratives follow those of standard-issue gold, silver, and clad coins.");

INSERT INTO CoinValue VALUES(4, "Double Eagle", 2000, "This largest denomination of all regular United States issues was authorized to be coined by the Act of March 3, 1849. The coin's weight was set at 516 grains, and its fineness at !!900. A single $20 gold pattern of 1849 resides in the Smithsonian.");

INSERT INTO CoinValue VALUES(5, "Eagle", 1000, "Coinage authorization, specified weights, and fineness of the eagle coins conform to those of the half eagle. The small eagle reverse was not used until 1797, when the large, heraldic eagle replaced it.");

INSERT INTO CoinValue VALUES(6, "Half Eagle", 500, "The half eagle ($5 gold coin) was the first gold coin struck for the United States. It was authorized to be coined by the Act of April 2, 1792. The first type weighed 135 grains, of !!91667 fineness. The weight was changed by the Act of June 28, 1834, to 129 grains, of !!899225 fineness. Fineness became !!900 by the Act of January 18, 1837.");

INSERT INTO CoinValue VALUES(7, "Four-Dollar Gold Piece", 400, "The Four Dollar Gold Piece or Stella is a pattern coin, which is a coin made as an example of a proposed coin. There are two very different looking types made in both 1879 and 1880. Charles Barber designed one with a Liberty head with flowing hair and George Morgan designed one with a Liberty head with coiled hair. Both types have a common reverse, that is a star with the words \"One Stella-400 cents.\" The minting of both these \"patterns\" took on the air of a competition between the two designers as they solicited Members of Congress with examples of their designs.

Stellas are very rare today, with the highest mintage being 415 pieces for the 1879 Flowing Hair piece. They were all struck as proofs and none were placed in circulation so most pieces encountered today are usually in a high state of preservation. Stellas are worth more than $50,000.");

INSERT INTO CoinValue VALUES(8, "Three-Dollar Gold Piece", 300, "The three-dollar gold piece was authorized by the Act of February 21, 1853. Coinage was struck beginning in 1854. It was never popular and saw very little circulation.");

INSERT INTO CoinValue VALUES(9, "Quarter Eagle", 250, "Although authorized by the Act of April 2, 1792, coinage of quarter eagles ($2!!50 gold coins) was not begun until 1796.");

INSERT INTO CoinValue VALUES(10, "Gold Dollar", 100, "Coinage of the gold dollar was authorized by the Act of March 3, 1849. The weight was 25!!8 grains, fineness !!900. The first type, struck until 1854, is known as the Liberty Head type.

In 1854, the piece was made larger in diameter and thinner. The design was changed to a feather headdress on a female, generally referred to as the Indian Princess Head type. In 1856 the type was changed slightly by enlarging the size of the head.");

INSERT INTO CoinValue VALUES(11, "Silver and Related Dollar", 100, "The silver dollar was authorized by Congress April 2, 1792. Its weight was specified at 416 grams and its fineness at !!8924. The first issues appeared in 1794, and until 1804 all silver dollars had the value stamped on the edge: HUNDRED CENTS, ONE DOLLAR OR UNIT. After a lapse in coinage of the silver dollar during the period of 1804 to 1835, coins were made of either plain (1836 only) or reeded edges and the value was placed on the reverse side.

The weight was changed by the law of January 18, 1837, to 412-1/2 grains, fineness !!900. The coinage was discontinued by the Act of February 12, 1873, and reauthorized by the Act of February 28, 1878. The silver dollar was again discontinued after 1935, and since then copper-nickel and other base-metal pieces have been coined for circulation.");

INSERT INTO CoinValue VALUES(12, "Half Dollar", 50, "The half dollar, authorized by the Act of April 2, 1792, was not minted until December, 1794. The weight of the half dollar was 208 grains and its fineness !!8924 when first issued. This standard was not changed until 1837 when the Act of January 18, 1837, specified 206-1/4 gains, !!900 fine. This fineness continued in use until 1965.

Arrows at the date in 1853 indicate the reduction of weight to 192 grains. During that year only, rays were added to the reverse. Arrows remained in 1854 and 1855. In 1873 the weight was raised by !!9 grains and arrows were again placed at the date.");

INSERT INTO CoinValue VALUES(13, "Quarter", 25, "Authorized in 1792, this denomination was not issued until four years later. The first type weighed 104 grains, the standard until modified to 103-1/8 grains by the Act of January 18, 1837. As with the dime and half dime, the weight was reduced and arrows placed at the date in 1853. Rays were placed in the field of the reverse during that year only.");

INSERT INTO CoinValue VALUES(14, "Twenty-Cent Piece", 20, "The twenty-cent piece was a short-lived coin authorized by the Act of March 3, 1875. The edge of the coin is plain. Most of the 1876-CC coins were melted at the Mint and never released. The mintmark is on the reverse below the eagle.");

INSERT INTO CoinValue VALUES(15, "Dime", 10, "The designs of the dimes, first coined in 1796, follow closely those of the half dimes up through the Liberty Seated type. The dimes in each instance weight twice as much as the half dimes.");

INSERT INTO CoinValue VALUES(16, "Half Dime", 5, "The half dime types present the same general characteristics as larger United States silver coins. Authorized by the Act of April 2, 1792, they were not coined until February 1795, although dated 1794. At first the weight was 20!!8 grains, and fineness !!8924. By the Act of January 18, 1837, the weight was slightly reduced to 20-5/8 grains and the fineness changed to !!900. Finally, the weight was reduced to 19!!2 grains by the Act of February 21, 1853.");

INSERT INTO CoinValue VALUES(17, "Nickel", 5, "The nickel, in American usage, is a five-cent coin issued by the United States Mint. Composed of 75% copper and 25% nickel, the piece has been struck since 1866.

The silver half dime, also equal to five cents, had been issued since the 1790s. The economic upset of the American Civil War drove gold and silver from circulation, and the government at first issued paper currency in place of low-value coins. In 1865, Congress abolished the five-cent fractional currency note after Spencer M. Clark, head of the Currency Bureau (today the Bureau of Engraving and Printing), placed himself on the denomination. As two-cent and three-cent pieces without precious metal content had been successfully introduced, Congress also authorized a five-cent piece of base metal; the Mint began striking this in 1866.

The Shield nickel, the initial design, was struck until 1883, when it was replaced by the Liberty Head nickel. As part of a drive to increase the beauty of American coinage, the Buffalo nickel was introduced in 1913; it was followed by the Jefferson nickel in 1938. In 2004 and 2005, special designs in honor of the bicentennial of the Lewis and Clark Expedition were issued. The Mint in 2006 reverted to using Jefferson nickel designer Felix Schlag's original reverse (or \"tails\" side), although substituting a new obverse by Jamie Franki. As of 2012, it costs more than eleven cents to produce a nickel; the Mint is exploring the possibility of bringing down the cost by using less expensive metals.");

INSERT INTO CoinValue VALUES(18, "Three-Cent Piece", 3, "The three cent coin has an unusual history. It was proposed in 1851 both as a result of the decrease in postage rates from five cents to three and to answer the need for a small-denomination, easy-to-handle coin. The three cent silver featured a shield on a six sided star on the obverse and the Roman numeral III on the reverse. The coin was initially composed of 75% silver and 25% copper to ensure that the coin would be considered real currency yet not worth melting down for the silver. The coins were physically the lightest weight coins ever minted by the United States, weighing only 4/5 of a gram and with a diameter smaller than a modern dime and only slightly greater than the smallest gold dollars. The silver coins were known as \"fishscales\". The term \"trimes\" is often used today for these coins but that was first used by the director of the United States Mint (James Ross Snowden) at the time of their production.

Starting in 1854, the three cent silver had its silver metal content raised to 90% in order to encourage circulation. At the same time, its weight was reduced to 3/4 of a gram by reducing thickness. The coin went through a design change at the time such that two lines were now used to border the star on the obverse and an olive sprig was added above and a bundle of arrows below the Roman numeral III on the reverse. A final design change occurred in 1859 because of striking problems: the number of lines bordering the star was reduced to one, and the font was made taller and slightly more narrow. The size of the date numerals also varied through the years, with 1860–1863 featuring the smallest date numerals of any US coin. In 1851 only, the New Orleans Mint struck some of the silver three-cent coins. It was minted from 1851 to 1873 at the Philadelphia Mint. In the later years there were very small mintages and the 1873 issue was in proof state only. However, an earlier date silver three cent piece can be bought in worn condition for a relatively low[vague] price. The silver three cent piece (along with the silver dollar, the half dime, and the two cent piece) was discontinued by the Coinage Act of 1873.

Civil War era silver shortages led to widespread hoarding of all silver coins, and most one and five cent coins as well. Various alternatives were tried, including encapsulated postage and privately issued coinage. The Treasury eventually settled on issuing fractional currency. These small denomination (1 to 50 cent) notes were never popular, as they were easy to lose and unwieldy in large amounts. The answer to this issue was reached in 1865 with the introduction of the three cent nickel coin. This coin was composed of copper and nickel and was larger than the silver coin of the same denomination. The coin featured a Liberty head obverse and another Roman numeral 'III' reverse. The three cent nickel was never intended as a permanent issue, only as stopgap measure until the wartime hoarding ceased. However, production of the coin continued until 1889, 16 years after the three cent silver was discontinued. One reason often given for the discontinuation of the three cent nickel piece in 1889 is that this coin and the dime (10 cent silver coin) were identical in diameter, and hence caused confusion upon the introduction of mechanical vending machines.[dubious – discuss] Another factor may have been that in 1883 the letter postage rate dropped to 2 cents, thus removing the justification for this coin.

The three cent nickel was only minted in Philadelphia and, except for a larger date on the 1889 pieces, had no design differences throughout its run. Over the course of the series mintage declined, and some of the dates are scarce. But, with an 1865 mintage of over eleven million, a type piece can be inexpensively obtained.");

INSERT INTO CoinValue VALUES(19, "Two-Cent Piece", 2, "The two-cent coin was produced in the United States from 1864–1873 with decreasing mintages throughout that time. Just over 45.5 million were produced.

The two-cent piece was authorized by Congress on April 22, 1864, by the Coinage Act. The same law also eliminated the half dime and the silver three-cent piece (the copper-nickel three-cent piece continued to be minted through 1889). During the mid- and late-1970s there was some discussion about reviving the two-cent denomination (in conjunction with reducing the mintage of the one-cent piece), but nothing came of it.

Two-cent pieces were minted in both proof and regular issues. Although the proof mintages were normally smaller than the regular-issue mintages, more proofs of high grade survive as they were always considered special collector coins.

While all two-cent pieces are of the same type, many die varieties exist. The most significant of these are the Small Motto and Large Motto varieties of 1864. The Small Motto is rarer and more valuable. Doubled dies, die cracks and other mint errors are often encountered in this series.

The two-cent piece was designed by James B. Longacre, the Chief Engraver of the United States Mint, and was the first coin of the United States to bear the motto \"In God We Trust.\" The design is similar to the shield nickel of the same period, which was also designed by Longacre.

The obverse (so designated because it bears the date) has a shield with a ribbon over it bearing the motto, IN GOD WE TRUST. Behind the shield are two arrows, and a branch with leaves (most likely an olive branch).

The reverse has a wreath made up of several different plant components surrounding the words 2 CENTS. The words UNITED STATES OF AMERICA surround the wreath.

The two-cent piece was made of 95% copper with tin and zinc making up the remainder. It was just slightly smaller than a modern U.S. quarter.");

INSERT INTO CoinValue VALUES(20, "Small Cent", 1, "The Small Cent has been with us since 1856. It succeeded the Large Cent, first introduced in 1793. By the time the Small Cent was introduced, its predecessor was already antiquated. Twice during the history of the Large Cent, the metal content of the coin became so expensive to purchase that the manufacture exceeded its face value.  The Large Cent had been unpopular since the 1840s. It was really too large, it became unsightly once it circulated and toned and it was too heavy. Since only silver and gold coins were legal tender, banks and merchants often refused to accept the coins in commerce unless they were deeply discounted below face value.

The final straw came when, in 1851, it began costing the Mint $1.06 to strike a dollar face value in 1-cent coins. Congressional lobbyists and Mint officials sprang into action. The lobbyists were particularly interested in ensuring nickel would be used in a new coin denomination since the nickel monopoly had significant influence on the Mint.  Mint officials began experimenting with pattern coins to see what alternatives to the costly Large Cent could be invented.  The impact from it wasn’t great at the time, but New York dentist Dr. Lewis Feuchtwanger proposed a Small Cent of what he called “argentan” or “American silver” (actually German silver composition) as early as 1837. It was this pattern that, intentionally or not, became the model for our Small Cent.  Joseph Wharton, who owned the nickel mines, got his way.  Mint Director James R. Snowden decided to strike a Small Cent of 88 percent copper and 12 percent nickel at a weight of 4.67 grams (Large Cents have a weight of 10.89 grams and are composed of pure copper beginning in 1795).

The first Small Cents, the Flying Eagle issue dated 1856, was actually made at Snowden’s direction without congressional approval. Although to this day no one has ever complained, technically this is an unauthorized issue falling under the same jurisdiction with the Secret Service as does the 1804 silver dollar, 1913 Liberty Head nickel and the 1933 Saint-Gaudens $20 double eagle. Of these non-authorized issues only the double eagle coin has ever been confiscated.  The Flying Eagle cent of 1856 is considered to be a pattern. The general issue coins of the same design are those of 1857 and 1858. The Christian Gobrecht design for the Flying Eagle appearing on the reverse of the Gobrecht dollar was used as the obverse for the cent. The reverse wreath by James B. Longacre was borrowed from the gold dollar and $3 coins already in circulation.No one really knows why the Flying Eagle design was so short lived, but the reason may be that it was so difficult to fully strike the design. The tail feathers are typically weak, even on Mint State specimens.

The Flying Eagle cent was followed by a one-year type Indian Head cent without a shield at the top of the closed laurel wreath on the reverse in 1859 and the design including the shield on the reverse above the open oak wreath between 1860 and 1909.  Longacre designed this coin entirely. The Indian Head cents of 1859 to 1864 are comprised of the same 4.67 grams of 88 percent copper and 12 percent nickel as the Flying Eagle cent.

The Small Cent began to resemble what we find in our pockets today during 1864 when the metal composition was changed to 95 percent copper, five percent tin and zinc with a reduced weight of 3.11 grams. The diameter remained at 19 millimeters.  There are some interesting coins in this series. Longacre’s initial “L” appears in the ribbon on the obverse of some of the later bronze composition 1864 cents, but was removed on later strikes. There is an important doubled die coin in 1873, 1877 is a scarce coin with a very low mintage and in 1908 the San Francisco Mint struck the 1-cent denomination for the first time (all 1-cent denomination coins were struck at Philadelphia until 1908; in 1911, the Denver Mint struck the cent denomination for the first time).

Although the Indian Head cent design proved to be popular, during 1909 it was announced the design would be changed mid-year in favor of a portrait of Abraham Lincoln designed by Victor D. Brenner to commemorate the centennial anniversary of Lincoln’s birth. Longacre had received criticism for the display of his initial on the Indian Head cent of 1864. Now Brenner received the same criticism for his initials VDB appearing on the 1909 cent.  The year 1909, as a result, has six major 1-cent coin types and varieties to collect. There is an Indian Head cent, a Lincoln cent with initials and another without; all struck at both Philadelphia without a Mint mark and at San Francisco with a Mint mark.

The new Lincoln cent obverse was destined to become the most consistent design in American coin history. It is still in use today and appears to be destined for continuous use at least through the 200th anniversary of Lincoln’s birth. Legislation is now being considered (in early 2000) for a special commemorative Cent to mark the anniversary.  Regarding Brenner’s initials, they were removed from the Cent beginning in 1910, however the initials were restored without fanfare below the truncation on the obverse beginning in 1918 and have appeared on the coin ever since.

The Lincoln/Wheat ears Cent of 1909 to 1958 includes some interesting rarities. The classics are the very low mintage 1914-D, the over-polished die resulting in the 1922-D without Mint mark issue, low mintage 1931-S and the classic error 1955 doubled die coin.  The Lincoln cent was introduced to the same metal specifications as the Indian Head cent of 1864 to 1909.  The metal content was changed to a 2.7 gram, zinc-coated steel coin in 1943 due to a shortage of other metals during World War II.  This became a one-year variety as the metal proved to be unpopular with the public. People claimed to confuse the 1943 cent with the dime. A numismatic writer said the steel cents were eventually dumped into the ocean where they poisoned the fish.  There are some rare off-metal strikes of the 1943 cent caused by copper blanks left in the coining hopper from the year before. Beware of 1943 coins sprayed with copper or altered 1948 cents.  Between 1944 and 1946 the cent was made from spent ammunition cartridge cases. The weight of the coin is 3.11 grams with a composition of 95 percent copper and five percent zinc. The 95 percent copper, five percent tin and zinc composition of earlier issues was resumed in 1947.

In 1959 the reverse of the Lincoln cent was changed to that of the Lincoln Memorial to mark the 150th anniversary of Lincoln’s birth. The new reverse design is by Frank Gasparro. Rumors circulated of a wheat ear reverse cent of 1959, but no genuine mule specimen has ever been encountered.  The Lincoln Memorial reverse made the Lincoln cent the first US coin on which the same person appears on both sides. A statue of Lincoln can be seen within the memorial. Since that time the 1999 New Jersey quarter dollar has been issued with George Washington appearing on both sides (Washington stands in the boat going across the Delaware River on the reverse).  Beginning in mid 1962, the composition of the Cent was altered to 95 percent copper and five percent zinc as a cost saving measure. Die modifications followed in 1969, 1973 and 1974. The diameter has never been altered since the Small Cent was introduced.  There are some interesting major varieties within the Lincoln Memorial reverse series, but the scarcest is the 1995 doubled die caused by a rotation of the pivot.");

INSERT INTO CoinValue VALUES(21, "Large Cent", 1, "Cents and half cents were the first coins struck under the authority of the United States government. Coinage began in 1793 with laws stating that the cent should weight exactly twice as much as the half cent. Large cents were coined every year from 1793 to 1857 with the exception of 1815, when a lack of copper prevented production. All were coined at the Philadelphia Mint. Varieties listed are those most significant to collectors. Numerous other die varieties may be found, as each of the early dies was individually made.");

INSERT INTO CoinValue VALUES(22, "Half Cent", .5, "The half cent was authorized to be coined April 2, 1792. Originally the weight was to have been 132 grains, but this was changed to 104 grains by the Act of January 14, 1793, before coinage commenced. The weight was again changed to 84 grains January 26, 1796, by presidential proclamation in conformity with the Act of March 3, 1795. Coinage was discontinued by the Act of February 21, 1857. All were coined at the Philadelphia mint.");

