DROP DATABASE IF EXISTS `CommonDB`;
DROP DATABASE IF EXISTS `UsCoinDB`;
DROP DATABASE IF EXISTS `ForeignCoinDB`;
DROP DATABASE IF EXISTS `OurCoinDB`;
DROP DATABASE IF EXISTS `OurForeignCoinDB`;
DROP DATABASE IF EXISTS `SearchDB`;
DROP DATABASE IF EXISTS `TrackerDB`;

CREATE DATABASE CommonDB;
CREATE DATABASE UsCoinDB;
CREATE DATABASE ForeignCoinDB;
CREATE DATABASE OurCoinDB;
CREATE DATABASE OurForeignCoinDB;
CREATE DATABASE SearchDB;
CREATE DATABASE TrackerDB;

